name: Release Clipper CLI

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.2.11"

      - name: Build Clipper CLI for Linux
        run: |
          deno task build:linux

      - name: Build Clipper CLI for macOS
        run: |
          deno task build:mac

      - name: Build Clipper CLI for Windows
        run: |
          deno task build:windows

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/clipper-x86_64-linux-gnu
            bin/clipper-aarch64-linux-gnu
            bin/clipper-x86_64-apple-darwin
            bin/clipper-aarch64-apple-darwin
            bin/clipper.exe
