name: Release Clipper CLI

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.46.2"

      - name: Build Clipper CLI for Linux
        run: |
          deno task build:x86_64-unknown-linux-gnu
          deno task build:aarch64-unknown-linux-gnu

      - name: Build Clipper CLI for macOS
        run: |
          deno task build:x86_64-apple-darwin
          deno task build:aarch64-apple-darwin

      - name: Build Clipper CLI for Windows
        run: |
          deno task build:x86_64-pc-windows-msvc
    
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/clipper-x86_64-unknown-linux-gnu
            bin/clipper-aarch64-unknown-linux-gnu
            bin/clipper-x86_64-apple-darwin
            bin/clipper-aarch64-apple-darwin
            bin/clipper.exe